import { Inter } from "next/font/google";
import "./globals.css";
import AdminHeader from "./header";
import AdminFooter from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha384-DyZ88mC6Up2uqS1lqnkGIEs6g+yg1KC8t5LD0JQFXK5PAMw5p1J43wYf5r/4cm5k"
          crossOrigin="anonymous"
        />
      </head>
      <body className={inter.className}>
        <AdminHeader />
        {children}
        <AdminFooter />
      </body>
    </html>
  );
}
